@startuml
start
:Clock initialized in NORMAL mode;

:Current Time requested \n by another component;

:Current system time is returned (20:00);

:Exactly 1 min passes;

:Current Time requested \n by another component;

:Current system time is returned (20:01);

stop
@enduml
