@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ProjectBookParser" as ProjectBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteProjectCommand" as DeleteProjectCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> ProjectBookParser : parseCommand("delete 1")
activate ProjectBookParser

create DeleteCommandParser
ProjectBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> ProjectBookParser
deactivate DeleteCommandParser

ProjectBookParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteProjectCommand
DeleteCommandParser -> DeleteProjectCommand
activate DeleteProjectCommand

DeleteProjectCommand --> DeleteCommandParser : d
deactivate DeleteProjectCommand

DeleteCommandParser --> ProjectBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> ProjectBookParser
destroy DeleteCommandParser

ProjectBookParser --> LogicManager : d
deactivate ProjectBookParser

LogicManager -> DeleteProjectCommand : execute()
activate DeleteProjectCommand

DeleteProjectCommand -> Model : deleteTrackedItem(trackedItemToDelete)
activate Model

Model --> DeleteProjectCommand
deactivate Model

DeleteProjectCommand -> Model : commitToHistory()
activate Model

Model --> DeleteProjectCommand
deactivate Model


create CommandResult
DeleteProjectCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteProjectCommand
deactivate CommandResult

DeleteProjectCommand --> LogicManager : result
deactivate DeleteProjectCommand

[<--LogicManager
deactivate LogicManager
@enduml
