@startuml
(*)  --> "FindType any selected"
--> New predicate created
--> "Individual predicate will test whether
any keyword matches the tracked item"
--> Individual predicates combined using logical OR
--> Combined predicate created
-->(*)
@enduml
