@startuml
(*)  --> "FindType none selected"
--> New predicate created
--> "Individual predicate will test whether
none of the keywords match the tracked item"
--> Individual predicates combined using logical AND
--> Combined predicate created
-->(*)
@enduml
