@startuml
!include detailed_style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
Interface ReadOnlyProjectBook <<Interface>>
Interface Model <<Interface>>
Class ModelManager {
displayList : ObjectProperty<ObservableList<TrackedItem>>
}
Interface ObservableList <<Interface>>
Class VersionedProjectBook
Class ProjectBook
Class ReadOnlyProjectBook
Class UserPrefs
Class ReadOnlyUserPrefs
Class "UniqueItemList<WorkDuration>"

Package Project {
Class "UniqueItemList<TrackedItem>"
Class TrackedItem
Class Project
Class Task
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

VersionedProjectBook --|> ProjectBook
ProjectBook .right.|> ReadOnlyProjectBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" VersionedProjectBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .left.|> ReadOnlyUserPrefs

ProjectBook *--> "1" "UniqueItemList<TrackedItem>"
"UniqueItemList<TrackedItem>" o--> "*" Project
Project --|> TrackedItem
Project *--> "*" Task
Task -left-|> TrackedItem
Project *-right-> "UniqueItemList<WorkDuration>" : durations
Task *-right-> "UniqueItemList<WorkDuration>" : durations


ModelManager -->"1" Project : current project
ModelManager -->"*" Project : observable list
ModelManager -->"*" Project : observable list of projects\n with active timers

@enduml
