@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyProjectBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class ProjectBook
Class ReadOnlyProjectBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Project {
Class Project
Class Description
Class DateWrapper
Class Name
Class Deadline
Class TimerWrapper
Class UniqueProjectList
Class UniqueDurationList
Class WorkDuration
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ProjectBook .up.|> ReadOnlyProjectBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" ProjectBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ProjectBook *--> "1" UniqueProjectList
UniqueProjectList o--> "*" Project
Project *--> Name
Project *--> Deadline
Project *--> DateWrapper
Project *--> Description
Project *--> TimerWrapper
Project *--> "*" Tag
Project *--> UniqueDurationList
UniqueDurationList o--> "*" WorkDuration

Name -[hidden]right-> Deadline
Deadline -[hidden]right-> Description
Description -[hidden]right-> DateWrapper
UniqueDurationList -[hidden]right-> TimerWrapper

ModelManager -->"1" Project : filtered list
ModelManager -->"*" Project : active timer list
@enduml
