@startuml
!include detailed_style.puml
autoactivate on

box Model MODEL_COLOR_T1
participant "project:Project" as Project MODEL_COLOR
participant ":ProjectBook" as ProjectBook MODEL_COLOR
participant ":ReminderTimerTask" as ReminderTimerTask MODEL_COLOR
participant "reminderManager:ReminderManager" as ReminderManager MODEL_COLOR
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

mainframe sd rescheduleReminder(project)
ProjectBook -> ReminderManager : rescheduleReminder(project)

group opt [canSchedule]
ReminderManager -> ReminderManager : scheduleReminder(project)

create ReminderTimerTask
ReminderManager -> ReminderTimerTask
return
return
end

group loop [until no tasks]
ReminderManager -> Project : rescheduleReminder(reminderManager)

Project -> ReminderManager : rescheduleReminder(project, task)

group opt [canSchedule]
ReminderManager -> ReminderManager : scheduleReminder(project, task)

create ReminderTimerTask
ReminderManager -> ReminderTimerTask
return
return
end

return
return
end

return
@enduml
