@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class TrackedItemListPanel
Class TrackedItemCard
Class BottomBar
Class CommandBox
Class ReminderDisplay
Class TimerListPanel
Class StatListPanel
Class TagsDisplay
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> TrackedItemListPanel
MainWindow *-down-> BottomBar
MainWindow *-down-> ReminderDisplay
MainWindow *-down-> TimerListPanel
MainWindow *-down-> StatListPanel
MainWindow *-down-> TagsDisplay

TrackedItemListPanel -down--> TrackedItemCard

MainWindow -left-|> UiPart

ResultDisplay ---|> UiPart
CommandBox ---|> UiPart
TrackedItemListPanel ---|> UiPart
TrackedItemCard ---|> UiPart
BottomBar ---|> UiPart
HelpWindow -down-|> UiPart
ReminderDisplay -----|> UiPart
TimerListPanel -----|> UiPart
StatListPanel -----|> UiPart
TagsDisplay -----|> UiPart

BottomBar ..> Model
ReminderDisplay ..> Model
TrackedItemCard ..> Model
TagsDisplay ..> Model
StatListPanel ..> Model
TimerListPanel ..> Model

UiManager -right-> Logic
MainWindow -left-> Logic

TrackedItemListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- BottomBar

MainWindow -[hidden]-|> UiPart
@enduml
