@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ProjectBookParser" as ProjectBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedProjectBook" as VersionedProjectBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> ProjectBookParser : parseCommand(undo)
activate ProjectBookParser

create UndoCommand
ProjectBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> ProjectBookParser
deactivate UndoCommand

ProjectBookParser --> LogicManager
deactivate ProjectBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoCommand()
activate Model

Model -> VersionedProjectBook : undo()
activate VersionedProjectBook

VersionedProjectBook -> VersionedProjectBook :resetData(ReadOnlyProjectBook)
VersionedProjectBook --> Model :
deactivate VersionedProjectBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
