@startuml
!include detailed_style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package Commons {
    class GuiThemeSettings {
        - {field} theme: Theme
    }

    class StatisticTimeframeSettings {
        - {field} statTimeframe : StatisticTimeframe
    }
}

package Model {
    class UserPrefs {
        + {method} returnChangedGuiThemeSettings(newGuiThemeSettings : GuiThemeSettings) : UserPrefs
        + {method} returnChangedStatisticTimeframeSettings(newTimeframeSettings : StatisticTimeframeSettings) : UserPrefs
    }
}

interface Serializable <<interface>>

GuiThemeSettings .up.|> Serializable
StatisticTimeframeSettings ..|>Serializable

GuiThemeSettings --o UserPrefs
StatisticTimeframeSettings --o UserPrefs

@enduml
